### ISSUE TITLE
sorry you are not allowed to upload....error

### ISSUE THREAD

**Issue by icode925** [algoritmika/marketplace-for-woocommerce#31]
vendor is try to upload store logo from their profile, after upload logo, they are getting error, You are not allowed to upload.

i am attachnig image for your ref.

https://imgur.com/v4NMDYF

**Comment by algoritmika** [comment]
Hi @icode925,

Thanks for reporting. Will be fixing that asap.

**Comment by algoritmika** [comment]
@icode925,

Update: While we are fixing it, it looks like the problem should be gone if you simply go to "WooCommerce > Settings > Marketplace > Vendors" and "Save changes" there.

**Comment by algoritmika** [comment]
Hi @icode925,

Fixed in plugin v1.4.0.
