### ISSUE TITLE
How to echo vendor gravatar from profile setting

### ISSUE THREAD

**Issue by procontentxyz** [algoritmika/marketplace-for-woocommerce#32]
echo get_avatar( get_the_author_meta( ‘ID’ ), 32 );

how to show gravatar before “By ~Avatar here~ Vendor Name” on all loop/archives.

https://developer.wordpress.org/reference/functions/get_avatar/

**Comment by pablo-sg-pacheco** [comment]
Hi @procontentxyz ,

I'm sorry. I'm not sure if I got what you mean. Can you please try to explain it again?

**Comment by procontentxyz** [comment]
how to show author photo (avatar) from profile.php page of wordpress.

in blog posts we show that using this function:

echo get_avatar( get_the_author_meta( ‘ID’ ), 32 );

ref: https://developer.wordpress.org/reference/functions/get_avatar/

**Comment by pablo-sg-pacheco** [comment]
Hi @procontentxyz ,
I've created a new option for you:
**- Vendors > Product loop info > Info's content**

In your case, you can also add there a `[alg_mpwc_vendor_img img_type="gravatar" gravatar_size="32"]`.
Let me know if it helps ;)

**Comment by procontentxyz** [comment]
Awesome 🤗

But you can do one thing also:

CSS for this gravatr/store logo,

So that it get shown just before store title.

**Comment by pablo-sg-pacheco** [comment]
No problem :)

In that case I think you can simply change the order of the **Info's content** option, like this for example:
```
<div>[alg_mpwc_vendor_img img_type="gravatar"]<a href="%store_url%">By %store_title%</a></div>
```

**Comment by procontentxyz** [comment]
![Screenshot_2021-11-30-08-51-53-778_com android chrome](https://user-images.githubusercontent.com/70431728/143980074-404084e9-9541-47cd-89f3-ee73fbfa1b25.jpg)

This is the result. :(

**Comment by procontentxyz** [comment]
this is how i solved the problem:


<style>
/* for gravatar */
img.avatar.avatar-32.photo,
/* for store_logo */
.avatar img {
    display: unset !important;
    vertical-align: middle !important;
    width: 32px !important;
    height: 32px !important;
    border-radius: 50% !important;
    margin:0 4px 0 0 !important;
}
</style>

**Comment by pablo-sg-pacheco** [comment]
Great!

**Comment by procontentxyz** [comment]
> Great!

Hmm...

Please resolve my latest issue #7
