### ISSUE TITLE
How to rearrange vendor name on loop

### ISSUE THREAD

**Issue by procontentxyz** [algoritmika/marketplace-for-woocommerce#33]
i am using below functions to remove and rearrange vendor name on loop archives:

```
remove_action( 'woocommerce_after_shop_loop_item', 'display_product_author_on_loop', 9 );
	
add_action( 'woocommerce_before_shop_loop_item_title', 'display_product_author_on_loop', 10 );

```

I tried to wrap these functions inside all possible functions:

```
add_action('init', 'remove_vendor_name_loop');
add_action('wp', 'remove_vendor_name_loop');
add_action('wp_loaded', 'remove_vendor_name_loop');
```

but these are not working.

please correct me if i am doing it wrong.

waiting for your reply.

Ref: https://plugins.trac.wordpress.org/browser/marketplace-for-woocommerce/trunk/classes/marketplace/user_roles/class-alg-mpwc-vendor-user.php#L42

**Comment by pablo-sg-pacheco** [comment]
Hi @procontentxyz ,

I've created a new hook for you. You could use it like this:

```
add_filter( 'alg_mpwc_loop_vendor_info_hook', function ( $filter ) {
    $filter = 'woocommerce_before_shop_loop_item_title';
    return $filter;
} );
```

Please update the plugin to version 1.4.8 and give it a try

**Comment by procontentxyz** [comment]
what about priority setting, kindly help

wanna set priority also.

rest all working like charm.

**Comment by pablo-sg-pacheco** [comment]
Hi @procontentxyz ,

Ok. I just created the 'alg_mpwc_loop_vendor_info_hook_priority' for you.
Please update the plugin to version 1.4.9.

You can use it like this:

```
add_filter( 'alg_mpwc_loop_vendor_info_hook_priority', function ( $priority ) {
    $priority = 99;
    return $priority;
} );
```

**Comment by procontentxyz** [comment]
Thats awesome
