### ISSUE TITLE
What is fucntion to get product vendor name

### ISSUE THREAD

**Issue by procontentxyz** [algoritmika/marketplace-for-woocommerce#35]
I want to show vendor name of current product on single product php file...using custom php fucntion

please tell me, how to display store name OR vendor name anywhere.

any shortcode?

any fucntion?

**Comment by pablo-sg-pacheco** [comment]
Hi @procontentxyz ,

Sorry for the delay.

If you simply want to get the vendor name:
```php
$vendor_user = get_user_by( 'ID', $vendor_user_id );
$vendor_name = $vendor_user->display_name;
```

If you want to get the store name:
```php
$store_name = get_user_meta( $vendor_user_id, '_alg_mpwc_store_title', true );
```

To find out the `$vendor_user_id` from a post/product you can simply access the `post_author` property:
```php
$vendor_user_id = $post->post_author
```
